name: Sentinel
authors: ['mcmonkey']
version: ${project.version} (build ${BUILD_NUMBER})
main: org.mcmonkey.sentinel.SentinelPlugin
depend: [Citizens]
softdepend: [Vault, Sentry]

commands:
  sentinel:
    description: Lists Sentinel commands.
    usage: /sentinel help
    permission: sentinel.basic

permissions:
  sentinel.*:
    description: Gives access to Sentinel commands.
    default: op
    children:
      # /sentinel
      sentinel.basic: true
      # /sentinel addtarget TYPE
      sentinel.addtarget: true
      # /sentinel removetarget TYPE
      sentinel.removetarget: true
      # /sentinel addignore TYPE
      sentinel.addignore: true
      # /sentinel removeignore TYPE
      sentinel.removeignore: true
      # /sentinel range RANGE
      sentinel.range: true
      # /sentinel damage DAMAGE
      sentinel.damage: true
      # /sentinel health HEALTH
      sentinel.health: true
      # /sentinel armor ARMOR
      sentinel.armor: true
      # /sentinel attackrate RATE
      sentinel.attackrate: true
      # /sentinel healrate RATE
      sentinel.healrate: true
      # /sentinel respawntime TIME
      sentinel.chaserange: true
      # /sentinel chaserange RANGE
      sentinel.respawntime: true
      # /sentinel guard PLAYER
      sentinel.guard: true
      # /sentinel invincible
      sentinel.invincible: true
      # /sentinel fightback
      sentinel.fightback: true
      # /sentinel needammo
      sentinel.needammo: true
      # /sentinel safeshot
      sentinel.safeshot: true
      # /sentinel chaseclose, chaseranged
      sentinel.chase: true
      # /sentinel drops
      sentinel.drops: true
      # /sentinel spawnpoint
      sentinel.spawnpoint: true
      # /sentinel forgive
      sentinel.forgive: true
      # /sentinel enemydrops
      sentinel.enemydrops: true
      # /sentinel kill
      sentinel.kill: true
      # /sentinel respawn
      sentinel.respawn: true
      # /sentinel sentryimport
      sentinel.sentryimport: true
      # /sentinel targettime TIME
      sentinel.targettime: true
      # /sentinel info, /sentinel targets, /sentinel stats
      sentinel.info: true
      # Edit other people's NPCs
      sentinel.admin: true
